version: "3.8"

services:
  db:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_DB: vita_track
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    networks:
      - server
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  server:
    driver: bridge
