services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # should we pass acme.email as an env or arg?
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:17.4
    secrets:
      - postgres_user
      - postgres_password
    environment:
      - POSTGRES_DB=vita_track
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vita-track-api:
    image: ghcr.io/perrysmithmoss/vita-track:${GIT_COMMIT_HASH:-latest}
    environment:
      - DATABASE_URL=/run/secrets/vita-track_database_url
      - GOOGLE_CLIENT_ID=/run/secrets/vita-track_google_client_id
      - GOOGLE_CLIENT_SECRET=/run/secrets/vita-track_google_client_secret
      - JWT_PRIVATE_KEY=/run/secrets/vita-track_jwt_private_key
      - JWT_PUBLIC_KEY=/run/secrets/vita-track_jwt_public_key
    secrets:
      - vita-track_database_url
      - vita-track_google_client_id
      - vita-track_google_client_secret
      - vita-track_jwt_private_key
      - vita-track_jwt_public_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.vita-track-api.loadbalancer.server.port=5500"
      # should we pass web.rule=Host as an env or arg?
      - "traefik.http.routers.vita-track-api.rule=Host(`vita-track-api.perrysmithmoss.com`)"
      - "traefik.http.routers.vita-track-api.entrypoints=websecure"
      - "traefik.http.routers.vita-track-api.tls.certresolver=myresolver"
    networks:
      - portfolio_network
    deploy:
      update_config:
        order: start-first
    depends_on:
      - postgres

volumes:
  postgres_data:
  letsencrypt:

networks:
  portfolio_network:
    external: true

secrets:
  vita-track_database_url:
    external: true
  vita-track_google_client_id:
    external: true
  vita-track_google_client_secret:
    external: true
  vita-track_jwt_private_key:
    external: true
  vita-track_jwt_public_key:
    external: true
