services:
  vita-track-api:
    image: ghcr.io/perrysmithmoss/vita-track:${GIT_COMMIT_HASH:-latest}
    env_file:
      - ./server/.env.production
    environment:
      - DATABASE_URL=/run/secrets/vita-track_database_url
      - GOOGLE_CLIENT_ID=/run/secrets/vita-track_google_client_id
      - GOOGLE_CLIENT_SECRET=/run/secrets/vita-track_google_client_secret
      - JWT_SECRET=/run/secrets/vita-track_jwt_secret
    secrets:
      - vita-track_database_url
      - vita-track_google_client_id
      - vita-track_google_client_secret
      - vita-track_jwt_secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.vita-track-api.loadbalancer.server.port=5500"
      - "traefik.http.routers.vita-track-api.rule=Host(`vita-track-api.perrysmithmoss.com`)"
      - "traefik.http.routers.vita-track-api.entrypoints=websecure"
      - "traefik.http.routers.vita-track-api.tls.certresolver=myresolver"
    networks:
      - portfolio_network
    deploy:
      update_config:
        order: start-first
    depends_on:
      - postgres

networks:
  portfolio_network:
    external: true

secrets:
  vita-track_database_url:
    external: true
  vita-track_google_client_id:
    external: true
  vita-track_google_client_secret:
    external: true
  vita-track_jwt_secret:
    external: true
