name: Deploy API to VPS

on:
  push:
    branches: [master]
    paths:
      - "server/**"
      - ".github/workflows/**"
      - "docker-stack.yaml"

jobs:
  #   run-tests:
  #     runs-on: ubuntu-latest
  #     steps:
  #         - uses: actions/checkout@v4
  #         # TODO...

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    # needs:
    #     - run-tests

    env:
      IMAGE_NAME: ghcr.io/perrysmithmoss/vita-track:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   sparse-checkout: |
        #     server
        #   sparse-checkout-cone-mode: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/perrysmithmoss/vita-track
          tags: |
            type=raw,value=${{ github.sha }}
            type=ref,event=branch
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: true
          progress: plain

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Automated release for commit ${{ github.sha }}
            Docker image: ${{ env.IMAGE_NAME }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
          echo "ACME_EMAIL=${{ secrets.ACME_EMAIL }}" >> ./envfile

      - name: Create server env file
        run: |
          mkdir -p server

          cat <<EOF > server/.env.production
          NODE_ENV=production
          SERVER_ENV=production
          PORT=5500
          SERVER_URL=https://vita-track-api.perrysmithmoss.com
          SERVER_DOMAIN=.perrysmithmoss.com
          ACCESS_TOKEN_COOKIE_NAME=accessToken
          ACCESS_TOKEN_TTL=${{ secrets.ACCESS_TOKEN_TTL }}
          REFRESH_TOKEN_COOKIE_NAME=refreshToken
          REFRESH_TOKEN_TTL=${{ secrets.REFRESH_TOKEN_TTL }}
          DEFAULT_USER_AVATAR_PATH=images/default-avatar.jpg
          CLIENT_URL=https://vita-track.vercel.app
          EOF

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: vita-track
          file: docker-stack.yaml
          host: ${{ secrets.VPS_IP }}
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
