name: Deploy API to VPS

on:
  push:
    branches: [master]
    paths:
      - "server/**"
      - ".github/workflows/**"

permissions:
  packages: write

jobs:
  #   run-tests:
  #     runs-on: ubuntu-latest
  #     steps:
  #         - uses: actions/checkout@v4
  #         # TODO...

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # needs:
    #     - run-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            server
          sparse-checkout-cone-mode: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
# TODO...
#   deploy:
#     runs-on: ubuntu-latest
#     needs:
#         - build-and-push-image
#     steps:
#           This step not needed?
#         - name: Checkout code
#           uses: actions/checkout@v2

#         - name: create env file
#           run: |
#             echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

#         - name: Docker Stack Deploy
#           uses: cssnr/stack-deploy-action@v1
#           with:
#               name: VitaTrack
#               file: docker-stack.yaml
#               host: perrysmithmoss.com # or IP address of VPS?
#               user: deploy
#               ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
#               env_file: ./envfile
